Availability accommodation
Avans-groep-N/Bumbodium pull request #49
Opened 2023-01-07 10:44 UTC by EvaVanGurp

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Added a boolean "IsConfirmed" to availabilities, where availabilities which are not confirmed (except for school hours) have to be manually confirmed by a manager in the accommodation screen. Availabilities which are denied are deleted from the database.

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

I ran through the process while looking at the database. First I added 5 availabilities: 3 school times, one sick leave and one vacation. Only the last two showed up in the accommodation screen. Then I accepted one and denied the other, the one I denied then turned to true and the other was deleted from the database. All the other data was still intact.

# Checklist:

- [x] My code runs
- [x] My code follows the coding guidelines
- [x] I rebased my branch on development
- [x] My code only has comments when necessary for understandability 
- [x] I removed commented out code
- [x] My code corresponds with the documentation
- [x] I have updated the documentation when changes were needed
- [x] All unit-tests succeeded (Except for not implemented exceptions)

# Optional:

- [ ] Is the branch linked to an issue?

2023-01-07 13:16 UTC, Enyuuus approved these changes

2023-02-01 12:58 UTC, Bewerkt requested changes
Spelvout that's all
(Weet ook niet of het nuttig is om deze na te kijken aangezien hij al een maand oud is bijna)

2023-02-01 12:58 UTC, Bewerkt commented on Bumbodium/Models/AvailabilityViewModel.cs
> +        public string[] Opdions = new[] { "Accepted", "Denied" };
Options?

2023-02-02 08:42 UTC, Bewerkt approved these changes

2023-02-02 09:13 UTC, merged